title: Quiet Hours
description: A book about stillness, isolation, and staying.
url: https://quiethours.art

theme: minima
markdown: kramdown

author: Erika Angelina

header_pages:
  - foreword/index.md

minima:
  show_excerpts: false
